### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ajbraus** [fchikwekwe/NameGenerator#1]
Hey there!

1. Super neat project idea. Love the modularization and separate API you are using.
1. Your heroku is errored out :( https://name-ly.herokuapp.com/
1. The naming of some of your resources are bit confusing. `NameList` is on the `/answers` route. A model probably wouldn't be called `NameList`, but just `Name`, and then an array of names would be a variable named `const nameList = Name.find()`. Consider carefully names of your routes, models, and resources so they are easy and natural to talk about. Your templates are named well with `names` as the root.
1. Your sign-up route is a bit smelly :D - the callbacks and statements make the code so deep logically. Can you break it up or use async/await to make it less "arrow shaped". e.g. I don't think you need the `if (!oldUser || oldUser == null) {` calls. 
1. `update.handlebars` is a bit of a weird name. 

Overall really clear that you are excelling and gaining speed. Focus on improving your naming and cleaning up your code smells. 

Great work!

**Comment by fchikwekwe** [comment]
Thanks for taking the time to leave feedback, @ajbraus !

- The Heroku link was missing some config vars; this is now fixed and the [link is live.](http://name-ly.herokuapp.com)
- The resource naming is appropriate for the structure of my NameList model. Right now each object has a set of names associated with it so that in the future I can show names with their respective authors and the timestamp from their quiz listed as well. I may consider coming back to this and changing it in the future, but for now I'm going to keep it as is. 
- Sign-up route has been refactored with async await; you can unplug your nose now! 😄 
- Update.handlebars is a template for updating the name list before submitting it to the user's profile. If you have a better suggestion for the name of that template, feel free to comment here. Open to suggestions. 

Otherwise, I'll go ahead and close this issue.
